version: "3.9"

services:
  api:
    container_name: api
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - redistimeseries
    environment:
      - NODE_ENV=production
      - BROKER_HOST=redistimeseries
      - BROKER_PORT=6380

  # Share cpu temp: https://stackoverflow.com/questions/72563504/get-raspis-cpu-temperature-within-docker-container
  # Share GPIO: https://stackoverflow.com/questions/30059784/docker-access-to-raspberry-pi-gpio-pins

  redistimeseries:
    container_name: redistimeseries
    image: redislabs/redistimeseries
    ports:
      - "6380:6379"
